### ISSUE TITLE
No padding on home page at certain width

### ISSUE THREAD

**Issue by adamopenweb** [webcompat/webcompat.com#1243]
There is a minor issue if the viewport is 1182px on the home page. The form has no padding and meets with the edge of the browser window. Looks a little odd.

<img width="1223" alt="scr" src="https://cloud.githubusercontent.com/assets/6587558/21273096/026cb626-c390-11e6-9b8f-d3dc8304616d.png">

**Comment by magsout** [comment]
```css
@media all and (max-width: 73.75em) {

    .wc-UIContent {
      width:auto;
      padding-left: 1em;
      padding-right: 1em;
    }
  }
```
Wrong media querie

Maybe something like:

```css
@media all and (max-width: 75em) {

    .wc-UIContent {
      width:auto;
      padding-left: 1em;
      padding-right: 1em;
    }
  }
```
