### ISSUE TITLE
Polishing the comment box design

### ISSUE THREAD

**Issue by karlcow** [webcompat/webcompat.com#1261]
In the 2016 design iteration, the comment box looks like:
![capture d ecran 2016-12-26 a 14 31 50](https://cloud.githubusercontent.com/assets/505230/21476144/5fcf5e0a-cb78-11e6-8ecc-344ee4620ccb.png)

We knew it when we deployed the new version. It is time to fix it. 🤖

## remove the textarea border

```css
.wc-Comment-submit {
	font-size: 1rem;
	display: block;
	width: 100%;
	min-height: 128px;
	/* border-color: rgb(194, 194, 194); */
	/* border-style: solid solid dashed; */
	border-width: 0;
	padding: 1em;
	resize: vertical;
}
```

![capture d ecran 2016-12-26 a 14 38 26](https://cloud.githubusercontent.com/assets/505230/21476199/22bd0926-cb79-11e6-9308-16c6c3c8bd9e.png)

## Proposal for images upload.

```css
.wc-UploadForm--new {
	min-height: 35px;
	background-color: rgb(64, 64, 64);
	display: flex;
}

.wc-UploadForm {
	display: block;
	position: relative;
	text-align: center;
	min-height: 250px;
	cursor: pointer;
	z-index: 3;
}

.wc-UploadForm-wrapper {
	z-index: 2;
	margin-top: 1rem;
	padding: 1rem;
	border: 2px dashed rgb(204, 204, 204);
	border-radius: 15px;
	align-content: center;
	align-items: center;
	margin: 1rem auto;
}
.wc-UploadForm-label {
	position: relative;
	display: inline-block;
	margin-bottom: 5px;
	color: rgb(204, 204, 204);
	font-weight: 700;
	cursor: pointer;
	text-decoration: underline;
}
```

![capture d ecran 2016-12-26 a 15 06 24](https://cloud.githubusercontent.com/assets/505230/21476604/5b8c8a48-cb7d-11e6-9ce3-ab8054ada042.png)

**Comment by karlcow** [comment]
## Fixing the margin for buttons.

```css
.wc-Form-group {
	position: relative;
	/* margin-bottom: 1.6em; */
}
.wc-Comment-button {
	text-align: right;
	margin: 0.6em 0 0;
}
```

![capture d ecran 2016-12-26 a 15 15 45](https://cloud.githubusercontent.com/assets/505230/21476674/356f86f2-cb7e-11e6-88c0-9e98348d231c.png)

**Comment by karlcow** [comment]
The global overview for this **proposal** (open to comments).

![capture d ecran 2016-12-26 a 15 16 47](https://cloud.githubusercontent.com/assets/505230/21476698/6c192244-cb7e-11e6-855e-70192c501e6b.png)

**Comment by karlcow** [comment]
For the buttons to be still centered when wider viewport

```css
.wc-Comment-button {
	text-align: right;
	margin: 0.6em auto 0 auto;
	display: flex;
	flex-direction: row;
	justify-content: center;
}

.wc-Button {
	display: inline-block;
	margin-bottom: .5em;
	padding: .5em 2em;
	text-decoration: none;
	font-weight: 700;
	border-radius: 20px;
	color: rgb(0, 0, 0);
	text-align: center;
	vertical-align: middle;
	cursor: pointer;
	white-space: nowrap;
	font-size: inherit;
	line-height: normal;
	background-color: transparent;
	background-image: none;
	-webkit-user-select: none;
	-moz-user-select: none;
	-ms-user-select: none;
	user-select: none;
	-webkit-appearance: none;
	margin: 0 1em .5em 1em;
}
```
