### ISSUE TITLE
Ugly Thumbnail when there is a long url 

### ISSUE THREAD

**Issue by ioana-chiorean** [webcompat/webcompat.com#1264]
After I've logged this: https://github.com/webcompat/web-bugs/issues/4095 I got to see the thumbnail in Fennec. Not nice. 

Not sure if we can make anything about it but I though to log it in. 

![photo_2017-01-04_17-42-48](https://cloud.githubusercontent.com/assets/1391451/21648098/70c5b5fe-d2a5-11e6-985f-011936419df1.jpg)

**Comment by miketaylr** [comment]
Thanks @ioana-chiorean! I bet we could wrap it or something. @magsout?

**Comment by karlcow** [comment]
It's a very simple first bug.

We just need to add `word-wrap: break-word;`

```
.wc-Markdown a {
	color: rgb(0, 0, 0);
	text-decoration: underline;
	word-wrap: break-word;
}
```

**Comment by karlcow** [comment]
The code to modify:

```css
  /* link */
  .wc-Markdown a {
    color: var(--Markdown-color);
    text-decoration: underline;
}
```

https://github.com/webcompat/webcompat.com/blob/551aab6ac3df9d1722850e580d263321876d6dce/webcompat/static/css/development/components/markdown.css#L27
