### ISSUE TITLE
Potential bug - misnamed class in issue.css

### ISSUE THREAD

**Issue by heatherbooker** [webcompat/webcompat.com#1393]
Starting at line 145 in `issue.css`, there is a missing vowel (`.wc-Issue-lbels`) that to me looks suspiciously like a bug: 

```css
.wc-Issue-labels {
  margin-bottom: 2em;
}
/* FullScreen LabelEditor*/
@media all and (max-width: 23.43em) {

  .wc-Issue-lbels {
    position: relative;
  }
}
```

Should there be an `a` in the media query? 

Then again, if it hasn't been noticed, maybe it's not needed? Applying `position: relative` manually to the div doesn't seem to me to visibly change anything in FF or Opera.
