### ISSUE TITLE
Audit our image loader usage

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#1529]
Where do we show loader images and in what circumstances?

Related to #746 and #1000.

**Comment by miketaylr** [comment]
Ping @zoepage

**Comment by karlcow** [comment]
So going through
https://www.webpagetest.org/result/170727_M0_FAA/

I noticed that we were sending two upload images.
One is http://localhost:5000/img/upload-loader.svg
and the other one is http://localhost:5000/img/loader.gif

The SVG is used now on the site.

But there is still a request done for loader.gif from the CSS.

```css
.wc-Loader {
 display:none;
 position:fixed;
 background-image:url(../../../img/loader.gif);
 z-index:10;
 background-color:rgba(255,255,255,0);
 top:0;
 left:0;
 right:0;
 bottom:0;
 background-position:center center;
 background-repeat:no-repeat
}
```
