### ISSUE TITLE
code bottom is slightly cut off

### ISSUE THREAD

**Issue by karlcow** [webcompat/webcompat.com#1605]
@magsout this is a fallout of the previous fix in #1570

Go to https://webcompat.com/issues/7272
See how the bottom of lines are hidden.

![capture d ecran 2017-06-21 a 06 53 48](https://user-images.githubusercontent.com/505230/27357816-b2e30892-564e-11e7-8626-010d8480f487.png)

**Comment by karlcow** [comment]
With an outline.
![capture d ecran 2017-06-21 a 17 24 18](https://user-images.githubusercontent.com/505230/27374390-89c4e32e-56a6-11e7-81e7-329d0037deb3.png)

**Comment by karlcow** [comment]
With 

```css
.wc-Markdown pre > code {
	white-space: pre !important;
	outline: 1px solid red;
	padding: 0;
}
```

![capture d ecran 2017-06-21 a 17 26 34](https://user-images.githubusercontent.com/505230/27374454-d4fc0642-56a6-11e7-909f-84ccb59f8050.png)
