### ISSUE TITLE
no background-color on html/body

### ISSUE THREAD

**Issue by karlcow** [webcompat/webcompat.com#1845]
1. Go to https://webcompat.com/
2. Inspect element html and body

`background-color` is not defined but  `color` is defined as `#404040`

```css
body {
	font-family: HelveticaNeue-Light,"Helvetica Neue Light","Helvetica Neue",Helvetica,Arial,"Lucida Grande",sans-serif;
	font-size: 1em;
	font-weight: 300;
	color: #404040;
}
```

It's usually not a good idea from https://github.com/webcompat/web-bugs/issues/12621
