### ISSUE TITLE
Same color displayed for all "Popular labels" from a search that returned no results

### ISSUE THREAD

**Issue by softvision-oana-arbuzov** [webcompat/webcompat.com#2154]
URL: https://staging.webcompat.com/issues?page=1&per_page=50&state=open&stage=all&sort=created&direction=desc
Browser / Version: Firefox Nightly Mobile 60.0a1 (2018-02-18), Firefox Nightly Desktop 60.0a1 (2018-02-16), Chrome Desktop 64.0.3282.167, Chrome Mobile 64.0.3282.137 
Operating System: Windows 10 Pro, Google Pixel (Android 8.0.0) - 1080 x 1920 pixels (~441 ppi pixel density)

**Steps to Reproduce:**
1. Navigate to https://staging.webcompat.com/issues?page=1&per_page=50&state=open&stage=all&sort=created&direction=desc
2. Tap the "Search" field and type in a string that returns no results (e.g. Testtesttest).
3. After error message is displayed, observe suggestions - popular labels (e.g. android/chrome/firefox/ie).
4. Observe label color.

**Expected Behavior:**
Different color is displayed for the labels:
- android: 
```css
element {
    border-color: #48DE20;
}
```
- chrome: 
```css
element {
    border-color: #FFA500;
}
```
- firefox:
```css
element {
    border-color: #E50000;
}
```
- ie: 
```css
element {
    border-color: #3E8AE5;
}
```

**Actual Behavior:**
The same label color is displayed for all suggestion.
```css
.issue .label[class*="label-browser"] {
    border-color: rgba(255, 204, 0, 1);
}
```

**Note**
1. Affected area: 
```html
<p class="issue-labels">
      Please check your spelling or try a more general search. 
	<br>
      You can also search for popular labels like: 
		<a class="label label-browser-android" href="#" title="Labels : android" data-remotename="browser-android">android</a>
		<a class="label label-browser-chrome" href="#" title="Labels : chrome" data-remotename="browser-chrome">chrome</a>
		<a class="label label-browser-firefox" href="#" title="Labels : firefox" data-remotename="browser-firefox">firefox</a>
		<a class="label label-browser-ie" href="#" title="Labels : ie" data-remotename="browser-ie">ie</a>
</p>
```

Watchers:
@softvision-sergiulogigan
@softvision-oana-arbuzov

![screenshot-1519044074615](https://user-images.githubusercontent.com/12184325/36378359-29517cea-1583-11e8-8c9c-086fdb2f5548.jpg)
