### ISSUE TITLE
Add stylelint-order to .stylelintrc

### ISSUE THREAD

**Issue by Regaddi** [webcompat/webcompat.com#2225]
This is possibly totally opinionated, but in the past I made great experiences using [stylelint-order](https://www.npmjs.com/package/stylelint-order) in addition to the standard stylelint config.
I usually prefer the alphabetical order for CSS properties, so instead of wildly mixed property orders like

```css
.some-selector {
  font-size: 14px;
  color: black;
  width: 100px;
  height: 50px;
}
```

You'd get:

```css
.some-selector {
  color: black;
  font-size: 14px;
  height: 50px;
  width: 100px;
}
```

I personally think, that the alphabetical order is the most natural order we as a humans are used to.

Just wanted to drop this idea here 😄

What do you think?

@zoepage

**Comment by zoepage** [comment]
I actually don't have an opinion here as there are different approaches people prefer. 
@magsout what do you think?

**Comment by magsout** [comment]
it's an interesting discussion.

I usually write properties in a specific order like this:
```css
.foo {
/* display first */
display: block;
/* position */
position: static
/* padding, margin, top, left etc.. */
padding: 10em;
/* decoration, text etc.. */
text-align: center
}
```
But when you work on large css codebase with lot of contributors, you can't enforce this point of view because it's specific for yourself. I speak for me of course.

So, IMO, I think @Regaddi's idea is good. The order is logic and `natural`

💯 for me ;)
