### ISSUE TITLE
"Report bug" arrow is misaligned on Firefox on Linux

### ISSUE THREAD

**Issue by softvision-oana-arbuzov** [webcompat/webcompat.com#2367]
URL: www.staging.webcompat.com  
Browser / Version: Firefox Nightly 61.0a1 (2018-04-04), Firefox Release 59.0.2
Operating System: Linux Ubuntu 16.04

**Steps to Reproduce:**
1. Navigate to https://webcompat.com/ 
2. Observe “Report bug” arrow.

**Expected Behavior:**
Arrow is aligned (displayed on the right side of button label).

**Actual Behavior:**
Arrow is misaligned (displayed under button label).

**Note**
1. Not reproducible on Chrome.
2. Not reproducible on Windows 10 Pro.
3. Affected area:
```html
<button id="js-ReportBug" type="button" class="button button-hero is-closed">
        Report bug
      
	<svg class="icon-middle" role="presentation" aria-role="hide">
		<title>circle-right</title>
		<use class="button-icon-hero" xlink:href="#svg-circle-right">Report bug</use>
	</svg>
</button>
```
 
**Watchers:**
@softvision-sergiulogigan
@softvision-oana-arbuzov

sv; 

![arrowmisaligned](https://user-images.githubusercontent.com/12184325/38366776-89f40f98-38e9-11e8-84a0-24b93bb1e594.jpg)

**Comment by softvision-oana-arbuzov** [comment]
Removing from `width: 250px;`, the arrow becomes aligned.
```css
.button-hero {
    border-radius: 10px;
    font-size: 2em;
    background-color: var(--color-second);
    color: var(--color-first);
    font-weight: 200;
    width: 250px;
    vertical-align: middle;
}
```
![image](https://user-images.githubusercontent.com/12184325/38367126-7d5e1d54-38ea-11e8-9342-0516a7822b11.png)
