### ISSUE TITLE
Image should only have only max-width, not width:100%

### ISSUE THREAD

**Issue by karlcow** [webcompat/webcompat.com#2404]
Currently images in comments are shown with a `width: 100%`. It should not happen. Images which are smaller than the current width of the comment get blown out.

Just need to remove `width: 100%`

```css
.comment-body img, .js-Issue-markdown img {
	max-width: calc(var(--unit-modul-m) - (var(--unit-space) * 4));
	/* width: 100%; */
}
```
