### ISSUE TITLE
image overflows on small screen

### ISSUE THREAD

**Issue by magsout** [webcompat/webcompat.com#2441]
STR:
1) go to https://webcompat.com/issues/16742
2) reduce the size of the browser screen at 500px
3) images overflow its container

![img_0688](https://user-images.githubusercontent.com/1997108/39778065-9e390d60-5305-11e8-9b63-a9d0e201804e.PNG)

**Comment by Regaddi** [comment]
I am currently not sure, why we define this
```css
.comment-body img, .js-Issue-markdown img {
    max-width: calc(var(--unit-modul-m) - (var(--unit-space) * 4));
}
```
instead of this
```css
.comment-body img, .js-Issue-markdown img {
    max-width: 100%;
}
```
Needs some analysis and further testing.
