### ISSUE TITLE
Having a .prettierrc file in user directory causes linting errors when settings vary from default settings

### ISSUE THREAD

**Issue by mischah** [webcompat/webcompat.com#2459]
Without an .prettierrc file in the project prettier uses ~/.prettierrc which will cause thousands of linting errors if one has settings different from the default settings.

![image](https://user-images.githubusercontent.com/441011/40327075-dfff8c24-5d41-11e8-8499-2bf741ec0817.png)

# How to reproduce

Place a `.prettierrc` file with the following content in your user directory `~/`:

```yaml
# See https://prettier.io/docs/en/options.html for available options
# parser: flow
printWidth: 100
useTabs: true
singleQuote: true
bracketSpacing: false
```

--- 

PR over here: https://github.com/webcompat/webcompat.com/pull/2458
