### ISSUE TITLE
Code is now uppercased.

### ISSUE THREAD

**Issue by karlcow** [webcompat/webcompat.com#2768]
```css
.highlight {
	font-weight: 300;
	text-transform: uppercase;
}
```

See for example https://webcompat.com/issues/22453
This is another regression from the switch to markdown html sent by GitHub.
