### ISSUE TITLE
issues page: sitewait :hover turns bg white

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#290]
I'm not sure why--the following rule looks OK?

in issue-list.css:

``` css
  .IssueList-filtering--sitewait {
    border-color:var(--wc-state-sitewait);
  }
  .IssueList-filtering--sitewait:hover
  .IssueList-filtering--sitewait.is-active {
    background-color:var(--wc-state-sitewait);
  }
```
