### ISSUE TITLE
Check-marks are displayed misaligned on "Browser/Operating System" fields

### ISSUE THREAD

**Issue by softvision-oana-arbuzov** [webcompat/webcompat.com#3316]
**URL**: https://webcompat.com/issues/new

**Browser / Version**: Firefox Preview Nightly 200526 (🦎 78.0a1-20200522094316), Chrome 81.0.4044.138
**Operating System**: Huawei P20 Lite (Android 8.0.0) - 1080 x 2280 pixels, 19:9 ratio (~432 ppi density), Samsung Galaxy S6 Edge (Android 7.0) - 1440 x 2560 pixels (~577 ppi pixel density)

**Description**: Items are misaligned

**Steps to Reproduce**:
1. Navigate to https://webcompat.com/issues/new
2. Fill in and choose required data until reaching "Environment" section.
3. Tap "different device or browser" link.
4. Observe check-marks alignment.

**Expected Behavior:**
Check-marks are correctly aligned, on the right side of "Browser/Operating System" fields.

**Actual Behavior:**
Check-marks are displayed misaligned over the "Browser/Operating System" fields.

**Notes:**
1. Screenshot attached.
![Screenshot_3](https://user-images.githubusercontent.com/12184325/83002492-cc443180-a015-11ea-9cee-1e4c4e74c679.png)
2. Also reproducible on Firefox Nightly RDM.

Affected area:
```html
<div class="row mobile-col">
	<div class="form-element js-Form-group low with-validation-icons half is-validated js-no-error">
		<label class="form-label" for="browser">Browser</label>
		<small class="os-browser-error">Browser required</small>
		<input class="form-field text-field" id="browser" name="browser" type="text" value="Firefox 78.0">
	</div>
    <div class="form-element js-Form-group low with-validation-icons half is-validated js-no-error">
			<label class="form-label" for="os">Operating System</label>
			<small class="os-browser-error">OS required</small>
			<input class="form-field text-field" id="os" name="os" type="text" value="Windows 10">
	</div>
</div>
```

Watchers:
@softvision-oana-arbuzov
@cipriansv

**Comment by karlcow** [comment]
This can be "fixed" by 

```css

/* webcompat.css | https://webcompat.com/dist/webcompat.css */

.low.is-error::before, .low.is-validated::after {
  /* bottom: 32px; */
  bottom: 25px;
}

```

but it has still the same issue on using position absolute for something which should be just flexible depending on the fonts and the context.

why not instead of `:after` using a `:valid` selector on input.
with a background image which is an actual checkmark on a green background.

```css
.with-validation-icons.is-validated::after {
	background-color: var(--issue-selected-outline);
	background-image: url(e42190227ff4eb782f492de75c284239.svg);
}
```

@magsout opinions?

**Comment by magsout** [comment]
@karlcow my idea


```css
diff --git a/webcompat/static/css/src/issue-wizard-animations.css b/webcompat/static/css/src/issue-wizard-animations.css
index d1010107..22e8d85f 100644
--- a/webcompat/static/css/src/issue-wizard-animations.css
+++ b/webcompat/static/css/src/issue-wizard-animations.css
@@ -5,14 +5,14 @@
 @keyframes validated {
   0% {
     opacity: 0;
-    transform: scale(.8);
+    transform: scale(.8) translateY(-50%);
   }
   50% {
-    transform: scale(1.3);
+    transform: scale(1.3) translateY(-50%);
   }
   100% {
     opacity: 1;
-    transform: scale(1);
+    transform: scale(1) translateY(-50%);
   }
 }
```

```css
index 34072458..4ff8cb2f 100644
--- a/webcompat/static/css/src/issue-wizard.css
+++ b/webcompat/static/css/src/issue-wizard.css
@@ -443,8 +443,8 @@
   transition: box-shadow .3s;
 }
   transition: box-shadow .3s;
 }
 
-.with-validation-icons.is-validated::after,
-.with-validation-icons.is-error::before {
+.with-validation-icons.is-validated .input-wrapper::after,
+.with-validation-icons.is-error .input-wrapper::before {
   align-items: center;
   animation-duration: .25s;
   animation-fill-mode: forwards;
@@ -453,33 +453,35 @@
   background-repeat: no-repeat;
   background-size: 50%;
   border-radius: 50%;
-  bottom: 4px;
   content: "";
-  display: flex;
+  display: block;
   height: 19px;
   justify-content: center;
   opacity: 0;
   position: absolute;
   right: 8px;
-  top: auto;
   transition: opacity .2s;
   width: 19px;
   z-index: 2;
+  top: 50%;
+}
+
+.with-validation-icons .input-wrapper {
+  position: relative;
 }
 
-.with-validation-icons.is-validated::after {
+.with-validation-icons.is-validated .input-wrapper::after {
   background-color: var(--issue-selected-outline);
   background-image: url("../../img/svg/icons/svg-check-issue.svg");
 }
 
-.with-validation-icons.is-error::before {
+.with-validation-icons.is-error .input-wrapper::before {
   background-color: var(--wizard-step-error);
   background-image: url("../../img/svg/icons/svg-cross-white.svg");
 }
 
-.low.is-validated::after,
-.low.is-error::before {
-  bottom: 32px;
+.low.is-validated .input-wrapper::after,
+.low.is-error .input-wrapper::before {
   height: 20px;
   right: 18px;
   width: 20px;
@@ -1052,24 +1054,21 @@
     padding: 25px 0 14px 0;
   }
 
-  .with-validation-icons.is-validated::after,
-  .with-validation-icons.is-error::before {
-    bottom: 8px;
+  .with-validation-icons.is-validated .input-wrapper::after,
+  .with-validation-icons.is-error .input-wrapper::before {
     height: 24px;
     right: 8px;
     width: 24px;
   }
 
-  .low.is-validated::after,
-  .low.is-error::before {
-    bottom: 23px;
+  .low.is-validated .input-wrapper::after,
+  .low.is-error .input-wrapper::before {
     height: 20px;
     width: 20px;
   }
 
-  .step-custom-browser .low.is-validated::after,
-  .step-custom-browser .low.is-error::before {
-    bottom: 22px;
+  .step-custom-browser .low.is-validated .input-wrapper::after,
+  .step-custom-browser .low.is-error .input-wrapper::before {
     right: 8px;
   }
```

```html
diff --git a/webcompat/templates/issue-wizard-form.html b/webcompat/templates/issue-wizard-form.html
index 5dafc6f3..3dfea0a9 100644
--- a/webcompat/templates/issue-wizard-form.html
+++ b/webcompat/templates/issue-wizard-form.html
@@ -32,10 +32,11 @@
                 <small class="form-message-error">{{ error }}</small>
               {% endfor %}
             {% endif %}
-
+            <div class="input-wrapper">
             {{ form.url(class_='form-field text-field required',
                 placeholder='e.g. https://example.com',
                 required=True, type='url', pattern='') }}
+            </div>
           </div>
         </div>
       </div>
@@ -165,11 +166,15 @@
           <div class="row mobile-col">
             <div class="form-element js-Form-group low with-validation-icons half">
               {{ form.browser.label(class_='form-label') }}
-              {{ form.browser(class_='form-field text-field') }}
+              <div class="input-wrapper">
+                {{ form.browser(class_='form-field text-field') }}
+              </div>
             </div>
             <div class="form-element js-Form-group low with-validation-icons half">
               {{ form.os.label(class_='form-label') }}
-              {{ form.os(class_='form-field text-field') }}
+              <div class="input-wrapper">
+                {{ form.os(class_='form-field text-field') }}
+              </div>
             </div>
           </div>
         </div>
```

<img width="450" alt="Screen Shot 2020-06-25 at 18 08 06" src="https://user-images.githubusercontent.com/1997108/85756135-d6d61180-b70e-11ea-83e2-bc4e7aaee4ba.png">
