### ISSUE TITLE
[bug] fenced markup and unknown syntax in comments

### ISSUE THREAD

**Issue by karlcow** [webcompat/webcompat.com#620]
When the syntax is unknown for the fenced markup. we get a simple `pre` element and  lack of margins above and below the block.
It makes the code/prose difficult to read.

Example [on one bug](https://webcompat.com/issues/1123#issuecomment-109099534)

![comments screenshot](https://cloud.githubusercontent.com/assets/505230/7997031/1448f478-0b62-11e5-87f8-ebc5c255beac.png)

**Comment by magsout** [comment]
- [ ]   `pre` white-space: normal
- [ ]  `code` white-space : normal

**Comment by karlcow** [comment]
hmmm I was to quick for this one. This destroys even more the layout. :)
https://github.com/webcompat/webcompat.com/pull/625

![capture d ecran 2015-06-10 a 06 38 19](https://cloud.githubusercontent.com/assets/505230/8070316/5a2a7764-0f3b-11e5-94c1-cf08b1af950f.png)

After this, we get:

``` css
  /* pre / code */
  .Comment-content pre,
  .Comment-content code {
    white-space: pre;
    margin: 2rem;
  }
```

![capture d ecran 2015-06-10 a 06 37 57](https://cloud.githubusercontent.com/assets/505230/8070326/70371044-0f3b-11e5-9a27-8fa4cbf68653.png)
