### ISSUE TITLE
New pre/code styles bug

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#631]
![](https://cldup.com/YNohmOOce_-2000x2000.png)

Unsure why, but it's fixed by removing the `padding: 1em` on 

```css
.wc-Comment-content code, .wc-Comment-content pre {
    padding: 1em;
    margin: 0.5em 0px;
    overflow: auto;
    background: #F5F2F0 none repeat scroll 0% 0%;
}
```

I'm going to do a hot-fix of `.wc-Comment-content code {padding: 0}` and push it to master. Then maybe @karlcow or @magsout can propose a better fix.

**Comment by miketaylr** [comment]
Fixed by https://github.com/webcompat/webcompat.com/commit/3b358925803d69f6cb2d57c99d6ee6736277454e.

@magsout if the "fix" is OK, can you close? If you have a better idea, can you send a PR?

**Comment by magsout** [comment]
hum, thanks for the hot fix. it's good.

**Comment by karlcow** [comment]
Interesting the issue appears when this is removed.

``` css
.wc-Comment-content code {
    padding: 0px;
}
```

And to understand how it is working, put this and play with the padding value.

``` css
.wc-Comment-content code {
    padding: 0px;
    outline: 1px red solid;
}
```
