### ISSUE TITLE
Width of Comment on Small screen

### ISSUE THREAD

**Issue by magsout** [webcompat/webcompat.com#940]
Comment doesn't take advantage of full with on small screen..

![capture d ecran 2016-03-03 a 21 49 35](https://cloud.githubusercontent.com/assets/1997108/13509061/f7e2d7a0-e189-11e5-8f7d-73044c6f42de.png)

**Comment by tsah20** [comment]
is it has something to do with the responsiveness of the website?

**Comment by magsout** [comment]
This line https://github.com/webcompat/webcompat.com/blob/master/webcompat/static/css/development/components/comment.css#L45

We need to add a media querie to handle this width only and only if `avatar`  is display. Without it,  `max-width` is useless.

Something like:

```css
  /* Body */
  .wc-Comment-body {
    position: relative;
    flex: 1;
    margin-left:.8em;
  }

  @media all and (min-width: 61.88em) {

    .wc-Comment-body {
      max-width: calc(100% - 59px);
    }
  }

```
