### ISSUE TITLE
comments layout issue with missing justify left

### ISSUE THREAD

**Issue by karlcow** [webcompat/webcompat.com#972]
![capture d ecran 2016-03-17 a 17 04 00](https://cloud.githubusercontent.com/assets/505230/13839985/c99abb90-ec62-11e5-8967-309b7e4f70c3.png)

You see how the username, the commented and the time is spread on the full width?

The block is

```html
<div class="wc-Comment-header">
        <span class="wc-Comment-owner js-Comment-owner">
          <a class="wc-Link" href="https://github.com/karlcow">karlcow</a>
        </span> commented <a class="wc-Link" href="#issuecomment-197734839">an hour ago</a>
</div>
```

with the style: 

```css
.wc-Comment-header {
	border-radius: 10px 10px 0 0;
	background-color: #f0f0f0;
	padding: .8em .8em .8em 1em;
	display: -webkit-box;
	display: -webkit-flex;
	display: -moz-box;
	display: -ms-flexbox;
	display: flex;
	-webkit-box-align: center;
	-webkit-align-items: center;
	-moz-box-align: center;
	-ms-flex-align: center;
	align-items: center;
	-webkit-box-pack: justify;
	-webkit-justify-content: space-between;
	-moz-box-pack: justify;
	-ms-flex-pack: justify;
	justify-content: space-between;
}
```

For it to work it needs an additional `div`

```html
<div class="wc-Comment-header">
  <div>
        <span class="wc-Comment-owner js-Comment-owner">
          <a class="wc-Link" href="https://github.com/karlcow">karlcow</a>
        </span> commented <a class="wc-Link" href="#issuecomment-197734839">an hour ago</a>
  </div>
</div>
```
